version: "3.0"
services:
  gerente-service:
      build:
        context: gerente-service
        dockerfile: Dockerfile
      image: gerente-service:0.0.1-SNAPSHOT
      ports: 
        - "5002:5002"
      depends_on:
          - gerente-db
      networks:
          - gerente-net
      environment:
          - DATABASE_HOST=gerente-db
  gerente-db:
      container_name: gerente-db
      image: postgres
      ports:
          - "5432:5432"
      networks:
          - gerente-net
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=password
networks:
  gerente-net:
      driver: bridge
  

        